// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tempdb.Model;

#nullable disable

namespace TempApi.Migrations
{
    [DbContext(typeof(TempContext))]
    [Migration("20240822130914_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Status.model.StatusClass", b =>
                {
                    b.Property<string>("fileId")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("percentage")
                        .HasColumnType("double");

                    b.HasKey("fileId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("tempdb.Model.MainModel", b =>
                {
                    b.Property<string>("Sheet_Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email_Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address_Line_1")
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Line_2")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Date_of_Birth")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("FY_2019_20")
                        .HasColumnType("float");

                    b.Property<float?>("FY_2020_21")
                        .HasColumnType("float");

                    b.Property<float?>("FY_2021_22")
                        .HasColumnType("float");

                    b.Property<float?>("FY_2022_23")
                        .HasColumnType("float");

                    b.Property<float?>("FY_2023_24")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone_no")
                        .HasColumnType("longtext");

                    b.HasKey("Sheet_Id", "Email_Id");

                    b.ToTable("MainModels");
                });

            modelBuilder.Entity("tempdb.Model.Temp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Temps");
                });
#pragma warning restore 612, 618
        }
    }
}
